# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker images

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push_images_to_docker_hub:
    name: Push images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push builder image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            baptistearno/typebot-builder:latest
            baptistearno/typebot-builder:${{ env.RELEASE_VERSION }}
          build-args: |
            SCOPE=builder

      - name: Build and push viewer image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            baptistearno/typebot-viewer:latest
            baptistearno/typebot-viewer:${{ env.RELEASE_VERSION }}
          build-args: |
            SCOPE=viewer
